# Generated by Django 5.2 on 2025-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_formule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
