# Generated by Django 5.2.3 on 2025-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_formule', '0003_team_image_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
