# Generated by Django 5.2.3 on 2025-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_formule', '0004_driver_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='number',
        ),
        migrations.AddField(
            model_name='driver',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='length_km',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
