# Generated by Django 5.2.3 on 2025-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna_formule', '0005_remove_driver_biography_remove_driver_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
